.TH LIBGPG-ERROR 1 "23 June 2003"
.SH NAME
gpg-error - program to convert GnuPG error numbers to text
.SH SYNOPSIS
.B  gpg-error NUMBER...
.SH DESCRIPTION
.PP
\fIgpg-error\fP is a tool that converts numeric GnuPG errors to a short
one-line textual description.
.
.SH OPTIONS
\fIgpg-error\fP does not accept any options.
