---
- hosts: all
  tasks:
    - name: Common platform independent tasks
      include_role:
        name: "./roles/common"
    - name: Common platform independent tasks
      include_role:
        name: "./roles/debian"
