# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

raise 'For best use install the vbguest plugin. See the README for details' unless Vagrant.has_plugin?("vagrant-vbguest")

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/jessie64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = true

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "./src", "/vagrant/src"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    # vb.memory = "1024"
  end

  config.vm.provision "file", source: "../common/.buildrc", destination: "/home/vagrant/.buildrc"
  config.vm.provision "file", source: "./files/.debian_pkgrc", destination: "/home/vagrant/.debian_pkgrc"

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", env: {"VERSION" => "2.1.2"}, inline: <<-SHELL
  
    ## Build Env
    apt-get update
    apt-get install -y autoconf automake autotools-dev
    apt-get install -y cmake
    apt-get install -y debhelper dh-make devscripts
    apt-get install -y fakeroot file 
    apt-get install -y git gnupg
    apt-get install -y lintian
    apt-get install -y patch patchutils pbuilder
    apt-get install -y perl python
    apt-get install -y quilt
 
    ## Installation Prereqs 
    apt-get -y install libxi-dev libxtst-dev qtbase5-dev \
    libqt5x11extras5-dev qttools5-dev qttools5-dev-tools \
    libgcrypt20-dev zlib1g-dev libyubikey-dev libykpers-1-dev

    ## Setup build environment variables
    echo "source /home/vagrant/.debian_pkgrc ">>/home/vagrant/.profile
    echo "source /home/vagrant/.buildrc ">> /home/vagrant/.profile

    ## Create directory structure
    mkdir /home/vagrant/build

    ## Fetch source from github
    wget -P /home/vagrant/build https://github.com/keepassxreboot/keepassxc/releases/download/$VERSION/keepassxc-$VERSION-src.tar.xz

  SHELL
end
