---

# Configure the build environment and user

- name: Create the group used for building artifacts
  group:
    name: builder
    state: present
  become: true

- name: Create the user that will be building artifacts
  user:
    name: builder
    shell: /bin/bash
    groups: builder
  become: true

- name: Create the directory to drop the source tarball into that we will be building
  file: path=/home/builder/project/ state=directory group=users owner=builder mode=0775
  become: true
  become_user: builder
